In [1]:
# Tensors are multidimensional arrays designed for mathematical an computational efficiency

In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [4]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU")

GPU is available
Using GPU:NVIDIA GeForce RTX 3050 6GB Laptop GPU


Creating a Tensor

In [6]:
# Using empty
a=torch.empty(2,3)#---------> This creates a 2,3 shaped tensor where it allocates a place in memeory and prints the value that are already in that memory
a

tensor([[9.9383e-32, 1.3915e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
#check type
type(a)

torch.Tensor

In [8]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
#using rand
torch.rand(2,3)

tensor([[0.4865, 0.9891, 0.2635],
        [0.3310, 0.6220, 0.2331]])

In [11]:
# use of seed
torch.manual_seed(20)
torch.rand(2,3)

tensor([[0.5615, 0.1774, 0.8147],
        [0.3295, 0.2319, 0.7832]])

In [12]:
torch.manual_seed(20)
torch.rand(2,3)

tensor([[0.5615, 0.1774, 0.8147],
        [0.3295, 0.2319, 0.7832]])

In [13]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# Other ways

# using arange
print("using arange ->",torch.arange(0,10))

#using linspace
print("using linspace ->",torch.linspace(0,10,10))

#using eye(idenetity mat)
print("uisng eye ->",torch.eye(4))

#using full
print("using full ->",torch.full((3,3),5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
uisng eye -> tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [16]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [22]:
torch.rand_like(x,dtype=float)

tensor([[0.8351, 0.5019, 0.7195],
        [0.5386, 0.9104, 0.4846]], dtype=torch.float64)

Tensor Data Types

In [23]:
# find data type
x.dtype

torch.int64

In [24]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=int)

tensor([1, 2, 3])

In [25]:
#using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mathematical operations

In [26]:
x=torch.rand(2,2)
x

tensor([[0.6257, 0.0379],
        [0.7130, 0.3229]])

In [27]:
#addition
x+2

#subtraction
x-2

#multiplication
x*3

# division
x/3

# int division
(x*100)//3

# mod
x%2

#power
x**2


tensor([[0.3914, 0.0014],
        [0.5084, 0.1043]])

Element wise operation 

In [28]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.9631, 0.2284, 0.4489],
        [0.2113, 0.6839, 0.7478]])
tensor([[0.4627, 0.7742, 0.3861],
        [0.0727, 0.8736, 0.3510]])


In [29]:
#add
a+b

tensor([[1.4258, 1.0026, 0.8350],
        [0.2839, 1.5575, 1.0988]])

In [30]:
#sub
a-b

tensor([[ 0.5004, -0.5458,  0.0629],
        [ 0.1386, -0.1897,  0.3968]])

In [31]:
#mul
a*b

tensor([[0.4456, 0.1769, 0.1733],
        [0.0154, 0.5974, 0.2625]])

In [32]:
# division
a/b

tensor([[2.0816, 0.2951, 1.1628],
        [2.9062, 0.7828, 2.1307]])

In [33]:
#power
a**b

tensor([[0.9828, 0.3188, 0.7340],
        [0.8931, 0.7175, 0.9030]])

In [34]:
# mod
a%b

tensor([[0.0377, 0.2284, 0.0629],
        [0.0659, 0.6839, 0.0459]])

In [35]:
c=torch.tensor([1,-2,3,-4])

In [36]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [37]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [38]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [39]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [40]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [41]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [42]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

Reduction Operation

In [48]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=float)
e

tensor([[1., 9., 7.],
        [9., 1., 6.]], dtype=torch.float64)

In [44]:
#sum
torch.sum(e)

tensor(30)

In [45]:
#sum along cols
torch.sum(e,dim=0)

tensor([12,  8, 10])

In [46]:
# sum along rows
torch.sum(e,dim=1)

tensor([22,  8])

In [50]:
# mean
torch.mean(e)

# same for row and col

tensor(5.5000, dtype=torch.float64)

In [51]:
# median
torch.median(e)

tensor(6., dtype=torch.float64)

In [53]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(9., dtype=torch.float64)
tensor(1., dtype=torch.float64)


In [55]:
#product
torch.prod(e)

tensor(3402., dtype=torch.float64)

In [56]:
# standard deviation
torch.std(e)

tensor(3.6742, dtype=torch.float64)

In [57]:
# variance
torch.var(e)

tensor(13.5000, dtype=torch.float64)

In [58]:
#argmax ----> it gives the index of the max ele
torch.argmax(e)

tensor(1)

In [59]:
# argmin --> it gives the index of the min ele
torch.argmin(e)

tensor(0)

Matrix Operations

In [62]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

print(f)
print(g)

tensor([[1, 2, 0],
        [9, 8, 9]])
tensor([[9, 7],
        [8, 5],
        [9, 0]])


In [63]:
# matrix mul
torch.matmul(f,g)

tensor([[ 25,  17],
        [226, 103]])

In [64]:
#dot product
vec1=torch.tensor([1,2])
vec2=torch.tensor([3,4])

torch.dot(vec1,vec2)

tensor(11)

In [67]:
#Transpose
print(f)
print(torch.transpose(f,0,1))

tensor([[1, 2, 0],
        [9, 8, 9]])
tensor([[1, 9],
        [2, 8],
        [0, 9]])


In [68]:
#det
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float)
print(h)
torch.det(h)

tensor([[5., 4., 6.],
        [4., 1., 6.],
        [8., 5., 8.]])


tensor(26.0000)

In [69]:
#inverse
torch.inverse(h)

tensor([[-0.8462, -0.0769,  0.6923],
        [ 0.6154, -0.3077, -0.2308],
        [ 0.4615,  0.2692, -0.4231]])

Comparision operations

In [71]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[6, 8, 4],
        [4, 2, 3]])
tensor([[4, 8, 1],
        [9, 1, 6]])


In [72]:
#greater than
print(i>j)

#less than
print(i<j)

#not equal to
print(i!=j)

# greater than equal to
print(i>=j)

#less than or equal to
print(i<=j)

tensor([[ True, False,  True],
        [False,  True, False]])
tensor([[False, False, False],
        [ True, False,  True]])
tensor([[ True, False,  True],
        [ True,  True,  True]])
tensor([[ True,  True,  True],
        [False,  True, False]])
tensor([[False,  True, False],
        [ True, False,  True]])


Special Functions

In [80]:
k= torch.randint(size=(2,3),low=0,high=10,dtype=torch.float)
k

tensor([[3., 3., 2.],
        [2., 7., 3.]])

In [83]:
#log
print(torch.log(k))

#exp
print(torch.exp(k))

#sqrt
print(torch.sqrt(k))

#sigmoid
print(torch.sigmoid(k))

#softmax
print(torch.softmax(k,dim=0))

#relu
print(torch.relu(k))

tensor([[1.0986, 1.0986, 0.6931],
        [0.6931, 1.9459, 1.0986]])
tensor([[  20.0855,   20.0855,    7.3891],
        [   7.3891, 1096.6332,   20.0855]])
tensor([[1.7321, 1.7321, 1.4142],
        [1.4142, 2.6458, 1.7321]])
tensor([[0.9526, 0.9526, 0.8808],
        [0.8808, 0.9991, 0.9526]])
tensor([[0.7311, 0.0180, 0.2689],
        [0.2689, 0.9820, 0.7311]])
tensor([[3., 3., 2.],
        [2., 7., 3.]])


Inplace operation

In [84]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.4358, 0.6081, 0.3038],
        [0.8100, 0.0780, 0.1568]])
tensor([[0.2707, 0.9171, 0.3526],
        [0.2564, 0.9027, 0.9937]])


In [85]:
m.add_(n)  # now result in stored in m

tensor([[0.7065, 1.5252, 0.6564],
        [1.0665, 0.9806, 1.1505]])

In [86]:
m.relu_() # applies relu and stored in m

tensor([[0.7065, 1.5252, 0.6564],
        [1.0665, 0.9806, 1.1505]])

Copying Tensor

In [87]:
a=torch.rand(2,3)
a

tensor([[0.3637, 0.9984, 0.2984],
        [0.7851, 0.3346, 0.6824]])

In [92]:
b=a  # shallow copy

In [89]:
b

tensor([[0.3637, 0.9984, 0.2984],
        [0.7851, 0.3346, 0.6824]])

In [90]:
a[0][0]=0
a

tensor([[0.0000, 0.9984, 0.2984],
        [0.7851, 0.3346, 0.6824]])

In [91]:
b

tensor([[0.0000, 0.9984, 0.2984],
        [0.7851, 0.3346, 0.6824]])

In [93]:
print(id(a))
print(id(b))

1842767020336
1842767020336


In [94]:
b=a.clone() # deep copy

In [95]:
print(id(a))
print(id(b))

1842767020336
1844205865936


Tensor Operations on GPU

In [96]:
torch.cuda.is_available()

True

In [97]:
device=torch.device('cuda')

In [98]:
# creating a new tenso on GPU
torch.rand((2,3),device=device) 

tensor([[0.7680, 0.9209, 0.5808],
        [0.9348, 0.4126, 0.8324]], device='cuda:0')

In [100]:
# moving an existing tensor to GPU
print(a)
a.to(device=device)

tensor([[0.0000, 0.9984, 0.2984],
        [0.7851, 0.3346, 0.6824]])


tensor([[0.0000, 0.9984, 0.2984],
        [0.7851, 0.3346, 0.6824]], device='cuda:0')

Reshaping Tensors

In [101]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [102]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [103]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [104]:
b=torch.rand(2,3,4)
b

tensor([[[6.6147e-01, 5.8837e-01, 4.9582e-01, 3.2829e-01],
         [1.9331e-01, 4.8163e-02, 3.9659e-01, 6.1360e-01],
         [8.6361e-04, 4.0270e-01, 1.9351e-02, 5.6496e-02]],

        [[8.9656e-01, 3.5206e-01, 7.5492e-01, 1.4732e-01],
         [6.7544e-01, 7.1040e-01, 3.8802e-01, 5.4746e-01],
         [4.2192e-01, 9.5245e-01, 7.8846e-01, 4.1404e-01]]])

In [105]:
#permute
b.permute(2,0,1)


tensor([[[6.6147e-01, 1.9331e-01, 8.6361e-04],
         [8.9656e-01, 6.7544e-01, 4.2192e-01]],

        [[5.8837e-01, 4.8163e-02, 4.0270e-01],
         [3.5206e-01, 7.1040e-01, 9.5245e-01]],

        [[4.9582e-01, 3.9659e-01, 1.9351e-02],
         [7.5492e-01, 3.8802e-01, 7.8846e-01]],

        [[3.2829e-01, 6.1360e-01, 5.6496e-02],
         [1.4732e-01, 5.4746e-01, 4.1404e-01]]])

In [106]:
#unsqueez -----> its used for adding a dim i required place
c=torch.rand(226,226,3)
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [107]:
#squeez ------> opp of unsqueez
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

NUmpy and pytorch

In [109]:
import numpy as np
a=torch.tensor([1,2,3])
print(a)
b=a.numpy()
print(b)
type(b)

tensor([1, 2, 3])
[1 2 3]


numpy.ndarray

In [110]:
c=np.array([1,2,3])
print(type(c))
d=torch.from_numpy(c)
print(type(d))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
