In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [3]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [4]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters={}
    L=len(layer_dims)
    for l in range(1,L):
        parameters['W' + str(l)]=np.ones((layer_dims[l-1],layer_dims[l]))*0.1
        parameters['b' + str(l)]=np.zeros((layer_dims[l],1))
    
    return parameters

In [5]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [6]:
def linear_forwared(A_prev,W,b):
    Z=np.dot(W.T,A_prev) + b
    return Z

In [7]:
# Forward Propagation
def L_layer_forward(X,parameters):
    A=X
    L=len(parameters)//2           # no of layers in neural network
    for l in range(1,L+1):
        A_prev=A
        Wl=parameters['W'+str(l)]
        bl=parameters['b'+str(l)]
        #print('A'+str(l-1)+": ",A_prev)
        #print('W'+str(l)+": ",Wl)
        #print('b'+str(l)+': ',bl)
        #print('--'*20)
        A=linear_forwared(A_prev,Wl,bl)
        #print('A'+str(l)+': ',A)

    return A,A_prev

In [8]:
X=df[['cgpa','profile_score']].values[0].reshape(2,1)
y=df[['lpa']].values[0][0]
parameters=initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X, parameters)

In [9]:
y_hat = y_hat[0][0]

In [10]:
(y-y_hat)**2

13.542399999999997

In [11]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [12]:
update_parameters(parameters,y,y_hat,A1,X)

In [13]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [14]:
# epoch implementation
parameters=initialize_parameters([2,2,1])
epochs=5
for i in range(epochs):
    loss=[]
    for j in range(df.shape[0]):
        X=df[['cgpa','profile_score']].values[j].reshape(2,1)
        y=df[['lpa']].values[j][0]

        # parameter initialisation
        y_hat,A1=L_layer_forward(X,parameters)
        y_hat=y_hat[0][0]
        update_parameters(parameters,y,y_hat,A1,X)
        loss.append((y-y_hat)**2)
    print('Epoch -',i+1,'loss -',np.array(loss).mean())
parameters

Epoch - 1 loss - 25.321744156025517
Epoch - 2 loss - 18.320004165722047
Epoch - 3 loss - 9.473661050729628
Epoch - 4 loss - 3.2520938634031613
Epoch - 5 loss - 1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

In [15]:
# Now implementing using keras
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [16]:
model=Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.get_weights()

[array([[-0.70892406,  0.82090557],
        [-0.9092511 ,  0.92697513]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.20030105],
        [0.16176665]], dtype=float32),
 array([0.], dtype=float32)]

In [19]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
             np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)]

In [20]:
model.set_weights(new_weights)

In [21]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [22]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 2s 3ms/step - loss: 27.8906
Epoch 2/75
4/4 [==============================] - 0s 2ms/step - loss: 27.5590
Epoch 3/75
4/4 [==============================] - 0s 2ms/step - loss: 27.2537
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 26.8963
Epoch 5/75
4/4 [==============================] - 0s 2ms/step - loss: 26.5611
Epoch 6/75
4/4 [==============================] - 0s 2ms/step - loss: 26.1995
Epoch 7/75
4/4 [==============================] - 0s 2ms/step - loss: 25.8366
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 25.4483
Epoch 9/75
4/4 [==============================] - 0s 2ms/step - loss: 25.0491
Epoch 10/75
4/4 [==============================] - 0s 2ms/step - loss: 24.6525
Epoch 11/75
4/4 [==============================] - 0s 2ms/step - loss: 24.2426
Epoch 12/75
4/4 [==============================] - 0s 2ms/step - loss: 23.8080
Epoch 13/75
4/4 [==============================] - 0s 2ms/ste

In [23]:
model.get_weights()

[array([[0.37370518, 0.37370518],
        [0.36574554, 0.36574554]], dtype=float32),
 array([0.27241665, 0.27241665], dtype=float32),
 array([[0.37303025],
        [0.37303025]], dtype=float32),
 array([0.20484255], dtype=float32)]

In [24]:
tensorflow.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]