Working on docs(Integer encode)

In [2]:
import numpy as np
docs=['go india',
      'india india',
      'hip hip hurray',
      'jeetega bhai jeetega india jeetega',
      'bharat mata ki jai',
      'kohli kohli',
      'sachin sachin',
      'dhoni dhoni',
      'modi ji ki jai',
      'inquilab zindabad']

In [1]:
from keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()  # if the text comes that is out of traing then it replaces it with "nothing"(oov_token)

In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
tokenizer.word_index

{'india': 1,
 'jeetega': 2,
 'hip': 3,
 'ki': 4,
 'jai': 5,
 'kohli': 6,
 'sachin': 7,
 'dhoni': 8,
 'go': 9,
 'hurray': 10,
 'bhai': 11,
 'bharat': 12,
 'mata': 13,
 'modi': 14,
 'ji': 15,
 'inquilab': 16,
 'zindabad': 17}

In [5]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [6]:
tokenizer.document_count # no of sentences in document

10

In [7]:
sequences=tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [8]:
from keras.utils import pad_sequences
sequences=pad_sequences(sequences,padding='post')

In [9]:
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]])

working on docs(Embedding)

In [10]:
len(tokenizer.word_index)

17

In [12]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [14]:
model1=Sequential()
model1.add(Embedding(17,output_dim=2,input_length=5))

model1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 5, 2)              34        
                                                                 
Total params: 34
Trainable params: 34
Non-trainable params: 0
_________________________________________________________________


In [15]:
model1.compile('adam','accuracy')

In [17]:
pred=model1.predict(sequences)      # converts each word to 2 dim vector
print(pred)

1/1 [==============================] - 0s 17ms/step
[[[-0.04991972 -0.03985704]
  [ 0.01618921 -0.03996243]
  [-0.02672242 -0.01008429]
  [-0.02672242 -0.01008429]
  [-0.02672242 -0.01008429]]

 [[ 0.01618921 -0.03996243]
  [ 0.01618921 -0.03996243]
  [-0.02672242 -0.01008429]
  [-0.02672242 -0.01008429]
  [-0.02672242 -0.01008429]]

 [[ 0.01242702  0.04143012]
  [ 0.01242702  0.04143012]
  [-0.01313574 -0.00100357]
  [-0.02672242 -0.01008429]
  [-0.02672242 -0.01008429]]

 [[ 0.03818835 -0.02884375]
  [ 0.02909097 -0.02939091]
  [ 0.03818835 -0.02884375]
  [ 0.01618921 -0.03996243]
  [ 0.03818835 -0.02884375]]

 [[ 0.01156734  0.01892048]
  [-0.00117343  0.04460512]
  [-0.04736559  0.0209539 ]
  [ 0.01653023 -0.02100332]
  [-0.02672242 -0.01008429]]

 [[-0.02829998  0.01903374]
  [-0.02829998  0.01903374]
  [-0.02672242 -0.01008429]
  [-0.02672242 -0.01008429]
  [-0.02672242 -0.01008429]]

 [[ 0.00377958 -0.0197781 ]
  [ 0.00377958 -0.0197781 ]
  [-0.02672242 -0.01008429]
  [-0.026722

Working on IMDB Dataset

In [18]:
from keras.datasets import imdb

In [19]:
(X_train,y_train),(X_test,y_test)=imdb.load_data()

In [20]:
print(X_train.shape,"      ",X_test.shape)

(25000,)        (25000,)


Padding each sentence

In [21]:
X_train=pad_sequences(X_train,padding='post',maxlen=100)  # input trimed to 100
X_test=pad_sequences(X_test,padding='post',maxlen=100)

In [22]:
X_train.shape

(25000, 100)

Building Simple RNN (integer encoded)

In [24]:
model=Sequential()

model.add(SimpleRNN(32,input_shape=(100,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,121
Trainable params: 1,121
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 39s 48ms/step - loss: 0.7531 - accuracy: 0.5060 - val_loss: 0.6929 - val_accuracy: 0.5114
Epoch 2/5
782/782 [==============================] - 39s 50ms/step - loss: 0.6926 - accuracy: 0.5146 - val_loss: 0.6949 - val_accuracy: 0.5081
Epoch 3/5
782/782 [==============================] - 39s 50ms/step - loss: 0.6926 - accuracy: 0.5114 - val_loss: 0.6936 - val_accuracy: 0.5109
Epoch 4/5
782/782 [==============================] - 40s 51ms/step - loss: 0.6927 - accuracy: 0.5089 - val_loss: 0.6942 - val_accuracy: 0.5101
Epoch 5/5
782/782 [==============================] - 42s 53ms/step - loss: 0.6927 - accuracy: 0.5096 - val_loss: 0.6946 - val_accuracy: 0.5108


Building Simple RNN (Embedding)

In [26]:
model2=Sequential()
model2.add(Embedding(10000,2))  # considering vocabulary as 10K
model2.add(SimpleRNN(32,return_sequences=False))
model2.add(Dense(1,activation='sigmoid'))

model2.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, None, 2)           20000     
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 21,153
Trainable params: 21,153
Non-trainable params: 0
_________________________________________________________________


In [27]:
model2.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
history=model2.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 137s 174ms/step - loss: 0.6671 - accuracy: 0.5763 - val_loss: 0.7924 - val_accuracy: 0.6235
Epoch 2/5
782/782 [==============================] - 203s 259ms/step - loss: 0.6030 - accuracy: 0.6695 - val_loss: 0.5780 - val_accuracy: 0.6867
Epoch 3/5
782/782 [==============================] - 74s 94ms/step - loss: 0.4109 - accuracy: 0.8160 - val_loss: 0.4100 - val_accuracy: 0.8159
Epoch 4/5
782/782 [==============================] - 58s 75ms/step - loss: 0.3125 - accuracy: 0.8738 - val_loss: 0.4119 - val_accuracy: 0.8111
Epoch 5/5
782/782 [==============================] - 58s 74ms/step - loss: 0.2676 - accuracy: 0.8976 - val_loss: 0.4144 - val_accuracy: 0.8306
